// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:fb8da842-07c1-430d-9026-40c24d298690';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'coolproject-hosting-mobilehub-394663106';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd25o260vemqcip.cloudfront.net';
var aws_mobile_analytics_app_id = '9d0d3de89b4d4c228c87ad34319cd1b2';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '2535ea26-4d86-4bab-94fa-ce09ceda4fa7';
var aws_project_name = 'cool_project';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'coolproject-mobilehub-394663106';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
